#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \AoC\General\Command\Puzzle1());
$application->add(new \AoC\General\Command\Puzzle2());

$application->run();
